version: "3"
services:
  react-app:
    build: react-app
    tty: true
    volumes:
      - react-app:/react-app
    ports:
      - "3000:3000"
    user: root

  express-app:
    build: express-app
    tty: true
    volumes:
      - express-app:/express-app
    ports:
      - "5000:5000"
      - "1025:1025"
    user: root
  db:
    build: mysql
    tty: true
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_USER: appuser
      MYSQL_PASSWORD: mysql
    expose:
      - '3306'
    ports:
      - '3307:3306'
volumes:
  react-app:
  express-app:
  mysql:
