version: "3"
services:
  db:
      build: ./
      tty: true
      volumes:
        - mysql:/var/lib/mysql
      environment:
        MYSQL_DATABASE: test
        MYSQL_ROOT_PASSWORD: mysql
        MYSQL_USER: appuser
        MYSQL_PASSWORD: mysql
      expose:
        - '3306'
      ports:
        - '3307:3306'
volumes: 
  mysql: